### ISSUE TITLE
Language detection

### ISSUE THREAD

**Issue by vsky279** [Kjwon15/bluebirdradio#18]
Hi, your client is something I was once looking for. However in order to make it usable for me I am missing one key feature. I follow people writing basically in two languages: English and Czech. Using one TTS engine does not work very well in such situation.

It would be ideal if the client can determine the language of the tweet and use corresponding TTS engine.

A simplified but still very good solution might be the possibility to manually override the default engine for selected followed accounts.

**Comment by tribela** [comment]
Honestly, I'd wanted to add this feature few years ago. But I almost quit Twitter and migrated to Mastodon.
On the other side, There are some related ways.

* Google TTS has "Always-on language detection" as experimental feature.
* Tootdon(Mastodon client, Not Twitter) using "language" attribute to select TTS engine to speak in many languages.

If Twitter's API has language tag for each tweet, Then we can implement that feature in general way.

BTW, Twitter will shutting down Streaming API and then this app won't work without paying to Twitter.
